# Generated by Django 5.0.2 on 2024-05-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioguideapp', '0049_rename_city_user_citys'),
    ]

    operations = [
        migrations.CreateModel(
            name='guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_name', models.CharField(max_length=30)),
                ('guide_price', models.CharField(max_length=30)),
            ],
        ),
    ]
